steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'was/petclinic_btc'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/kdt1-finalproject/yj-repo/yj-was:latest', '..']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/kdt1-finalproject/yj-repo/yj-was:latest']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'was/was-deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-northeast3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=yj-gke-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
