apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
image: asia-northeast3-docker.pkg.dev/kdt1-finalproject/yj-repo/yj-was:was-20250701-01
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "300m"
            memory: "384Mi"
          limits:
            cpu: "600m"
            memory: "768Mi"
      - name: cloudsql-proxy
image: asia-northeast3-docker.pkg.dev/kdt1-finalproject/yj-repo/yj-was:was-20250701-01
        command: ["/cloud_sql_proxy",
                  "-instances=kdt1-finalproject:asia-northeast3:yj-db=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
